image:
  repository: ryanwholey/test-app
  tag: d99d6ca6b464f1daa0717e1f1a05de94f43c89b2
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
