image:
  repository: ryanwholey/test-app
  tag: 1438a89f9b473c09878526b6205c66dc8aad6b1c
  pullPolicy: IfNotPresent

server:
  extraArgs: {}

  podAnnotations: {}
  replicaCount: 1

  resources: {}
  port: 3000

service:
  annotations: {}
  type: ClusterIP
