image:
  repository: ryanwholey/test-app
  tag: 258887444a81b8d15115a020b0e7794f88d48fe5
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
