image:
  repository: ryanwholey/test-app
  tag: 95268d4b1e56b3f4fdb240cf18becf6d03c3c81e
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
hooks:
  enabled: false
  slackToken: ""
