image:
  repository: ryanwholey/test-app
  tag: dfb6787e4e622efaa9f1b3ba725353fd85605661
  pullPolicy: IfNotPresent

server:
  extraArgs: {}

  podAnnotations: {}
  replicaCount: 1

  resources: {}
  port: 3000

service:
  annotations: {}
  type: ClusterIP
