image:
  repository: ryanwholey/test-app
  tag: 5a9c6a16ea25331fc730adf87ec264c22449b898
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
