image:
  repository: ryanwholey/test-app
  tag: ba13a767fff242f28f24f59e0e2e9f34f2814baf
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
