image:
  repository: ryanwholey/test-app
  tag: b811a728abe775a79d3ce40a6b29a5927b7188bd
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
