image:
  repository: ryanwholey/test-app
  tag: e65e947c3a65d4d49ecea4a04610b1fa121bd324
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
