image:
  repository: ryanwholey/test-app
  tag: 83a02c890b965250df32f50c9dc07d570a3ee405
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
