image:
  repository: ryanwholey/test-app
  tag: a78b9f1ff7a99b007dc513dba8b6bb6100a5f00d
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
hooks:
  enabled: false
  slackToken: ""
