image:
  repository: ryanwholey/test-app
  tag: ec9405f6a7180676709315f4a9f3efbb80b9a28d
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
