image:
  repository: ryanwholey/test-app
  tag: 2904a37ddd256d928747adcad7cea3bf5426452b
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
