image:
  repository: ryanwholey/test-app
  tag: 7615377c3d207ecdb71a2046e4e45e7c3fbf8831
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
