image:
  repository: ryanwholey/test-app
  tag: 801906ccaadbaef2b7fc3892f6a20900ecc63007
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 3
  resources: {}
  port: 3000
  progressDeadlineSeconds: 120
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
hooks:
  enabled: false
  slackToken: ""
