image:
  repository: ryanwholey/test-app
  tag: d335d8ffea426eb8256a861e42ea5dcf17a03415
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 3
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
hooks:
  enabled: false
  slackToken: ""
