image:
  repository: ryanwholey/test-app
  tag: 7301cd3ad479489f98559808bf9481aea1552d97
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
