image:
  repository: ryanwholey/test-app
  tag: 74b5b088f70262c51bb9e1634e88f86df747ef10
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
