image:
  repository: ryanwholey/test-app
  tag: 19e74d7b87e1009fe217f03d8efcbb4c616c2592
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
