image:
  repository: ryanwholey/test-app
  tag: 53b5fb93d00ce5e698b730701973bf5a9dfef6cc
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
