image:
  repository: ryanwholey/test-app
  tag: 68e63fe4437c67fef8ae3b907705778f80426054
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
