image:
  repository: ryanwholey/test-app
  tag: 68c7d1ae70c05c8a6ad470fbbcd40089ee553a45
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
