image:
  repository: ryanwholey/test-app
  tag: a3e52871ad7c1ea799dd28be196c2c32ffe9fc25
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
