image:
  repository: ryanwholey/test-app
  tag: 1a20ea0bd15ac344de9e03a7dbb8df968c845b15
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
