image:
  repository: ryanwholey/test-app
  tag: 89b226dcbe40037ec211a19ffdf5bf8020c441b5
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
