image:
  repository: ryanwholey/test-app
  tag: 5bcc91b6cd9249e84334c9402239ea44a527909b
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
