image:
  repository: ryanwholey/test-app
  tag: 6de1ee2c2d1b41340137a29e5e778afa26eb82e2
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 3
  resources: {}
  port: 3000
  progressDeadlineSeconds: 120
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
hooks:
  enabled: false
  slackToken: ""
