image:
  repository: ryanwholey/test-app
  tag: 3de5f9c003f9530dac7dae99a9f9bd47024cc3f3
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  tld: ryanwholey.com
  name: app
