image:
  repository: ryanwholey/test-app
  tag: f8c3c8ba8ea5cee827a955217b9f0c38577081b7
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 3
  resources: {}
  port: 3000
  progressDeadlineSeconds: 120
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
hooks:
  enabled: false
  slackToken: ""
