image:
  repository: ryanwholey/test-app
  tag: ee5caf02d8aabdb35571f721f8d19f471886873b
  pullPolicy: IfNotPresent
server:
  extraArgs: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  port: 3000
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: true
  tld: ryanwholey.com
  name: app
hooks:
  enabled: false
  slackToken: ""
