version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  publish:
    docker:
      - image: cimg/python:3.6
    working_directory: ~/test-app-helm
    steps:
      - checkout
      - run: 
          name: Install yq
          command: pip install yq
      - run:
          name: Install helm
          command: curl -fsSL https://get.helm.sh/helm-v3.2.4-linux-386.tar.gz | sudo tar xz --strip-components=1 -C /usr/local/bin linux-386/helm
      - run:
          name: Export version
          command: |
            echo "export CHART_VERSION=$(cat Chart.yaml | yq  -r '.version')" >> $BASH_ENV
            echo "export CHART_NAME=$(cat Chart.yaml | yq  -r '.version')" >> $BASH_ENV
      - run:
          name: Package helm chart
          command: helm package .
      - run:
          command: ls
      - aws-s3/copy:
          from: ./${CHART_NAME}-${CHART_VERSION}.tgz
          to: 's3://wholey-helm-charts'
workflows:
  version: 2
  untagged-build:
    jobs:
      - publish:
          context: publish
