apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    helm.sh/chart: {{ template "name" . }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: server
  type: {{ .Values.service.type }}
